### ISSUE TITLE
Laggy frame

### ISSUE THREAD

**Issue by Zumbalamambo** [luigivieira/emotions#2]
I tried this code with my cpu.
why the frame is laggy? how can i be able to optimize it?

**Comment by luigivieira** [comment]
Hi there. The frame is laggy because the processing on each frame certainly takes some time. First of all, the code needs to track the face landmarks. That part is quite fast because the library used (dlib) makes a very good work in just adjusting the landmarks found in the previous frame into the current one and also because I did a trick to reduce the size of the image just for the detection. Then, the code extracts the responses for a bank of Gabor filters for each landmark position, and that bit is expensive. It applies 32 filters (8 orientations times 4 wavelengths) only to the face region (cropped from the original frame based on the landmarks found), but even though that is a lot of convolution to perform! Each filter has to be applied twice with the real and imaginary parts of the filter, so the magnitude can be obtained as the responses. That is indeed the features used by the SVM classifier to try to predict the emotions.

If you want a near real-time processing, you will have to use a GPU to parallelize the convolutions. The code I created uses OpenCV for the filter application (check out the calls for `cv2.filter2D` in Gabor.py). OpenCV has some integration with GPU ([details here](http://docs.opencv.org/2.4/modules/gpu/doc/introduction.html)) but you will have to use a different version of these calls and compile OpenCV with the proper integration. At the time I created the code I didn't need real-time processing and it was also not very easy to have it smoothly running in Python (the integration was mainly thought for C++). Hence, it was not in my priorities. Nonetheless OpenCV was used considering the future possibility of implementing that. :)

Cheers,
Luiz
