### ISSUE TITLE
cannot convert float infinity to integer

### ISSUE THREAD

**Issue by zhaoxuyan** [luigivieira/emotions#3]
I use cmd like this: `python test.py -i 0`
and I received the error:
```shell
$ python test.py -i 0
/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/skimage/filters/_gabor.py:76: RuntimeWarning: divide by zero encountered in double_scalars
  sigma_x = _sigma_prefactor(bandwidth) / frequency
/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/skimage/filters/_gabor.py:78: RuntimeWarning: divide by zero encountered in double_scalars
  sigma_y = _sigma_prefactor(bandwidth) / frequency
/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/skimage/filters/_gabor.py:81: RuntimeWarning: invalid value encountered in double_scalars
  np.abs(n_stds * sigma_y * np.sin(theta)), 1))
/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/skimage/filters/_gabor.py:83: RuntimeWarning: invalid value encountered in double_scalars
  np.abs(n_stds * sigma_x * np.sin(theta)), 1))
Traceback (most recent call last):
  File "test.py", line 503, in <module>
    main(sys.argv[1:])
  File "test.py", line 244, in main
    data = VideoData()
  File "test.py", line 57, in __init__
    self._bank = GaborBank()
  File "/Users/zhaoxuyan/Documents/GitHub/emotions/gabor.py", line 153, in __init__
    kernel = gabor_kernel(frequency, orientation)
  File "/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/skimage/filters/_gabor.py", line 84, in gabor_kernel
    y, x = np.mgrid[-y0:y0 + 1, -x0:x0 + 1]
  File "/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/numpy/lib/index_tricks.py", line 167, in __getitem__
    int(math.ceil((key[k].stop - start)/(step*1.0))))
OverflowError: cannot convert float infinity to integer
Cleaned up camera.
```

**Comment by luigivieira** [comment]
Hi @zhaoxuyan. Check out the project's Readme file. You will notice that there is a requirement for Python 3, and you seem to be using Python 2.7. That "division by zero" error is because of that dependency.

For the gabor filters, the function in the Scikit-Image package expects a frequency, but I use a wavelength (because that is the measurement [traditionally used in the equations](https://en.wikipedia.org/wiki/Gabor_filter)). I convert the wavelength to frequency as this: `f = 1/w`. The problem is that [in Python 2.7 that division produces an integer](https://ideone.com/GgXKcG), so the value is being truncated to 0. [In Python 3.x the division produces a float](https://ideone.com/4NKJcX) **as intended**, so the division by zero error does not occur.

You can use the targeted Python version as described in the readme or change the code yourself in your own fork to fix the "error". Additional info can be found [in this thread from StackOverflow](https://stackoverflow.com/q/1267869/2896619).

Cheers

**Comment by zhaoxuyan** [comment]
Thank you !
I have already fixed my problems !
It 's very Awesome

**Comment by luigivieira** [comment]
Thank you. Glad you liked it. Cheers.
